version: 2
updates:

- package-ecosystem: "github-actions"
  open-pull-requests-limit: 99
  directory: "/"
  rebase-strategy: "disabled"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"

# frontend
- package-ecosystem: docker
  open-pull-requests-limit: 99
  directory: "/"
  rebase-strategy: "disabled"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"
- package-ecosystem: npm
  open-pull-requests-limit: 99
  directory: "/"
  rebase-strategy: "disabled"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"
  groups:
    linting:
      applies-to: version-updates
      patterns:
        - "*textlint*"
    vuepress:
      applies-to: version-updates
      patterns:
        - "*vuepress*"

# backend
- package-ecosystem: docker
  open-pull-requests-limit: 99
  directory: "/backend"
  rebase-strategy: "disabled"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"
- package-ecosystem: npm
  open-pull-requests-limit: 99
  directory: "/backend/"
  rebase-strategy: "disabled"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"
  groups:
    linting:
      applies-to: version-updates
      patterns:
        - "*textlint*"