name: auto-merge

on:
  pull_request:

jobs:
  auto-merge:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
      - uses: ahmadnassri/action-dependabot-auto-merge@4b9c6f0185a1c94f18bc293dc050c8c073b4fcc8 #v2.6.6
        with:
          target: minor
          github-token: ${{ secrets.DEPENDABOT_AUTOMERGE_TOKEN }}