name: backend:test:lint

on: push

jobs:
  files-changed:
    name: Detect File Changes - lint
    runs-on: ubuntu-latest
    outputs:
      lint: ${{ steps.filter.outputs.lint }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4.1.7
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          filters: |
            lint:
              - '.github/workflows/**/*'
              - 'backend/**/*'

  lint:
    if: needs.files-changed.outputs.lint == 'true'
    name: Lint
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4.1.7
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v4.0.3
        with:
          node-version-file: './.tool-versions'
      - name: Lint
        run: npm install && npm run lint
        working-directory: ./backend
