name: test:unit

on: push

jobs:
  files-changed:
    name: Detect File Changes - unit
    runs-on: ubuntu-latest
    outputs:
      unit: ${{ steps.filter.outputs.unit }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4.1.7
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          filters: |
            unit:
              - '.github/workflows/**/*'
              - 'backend/**/*'

  unit:
    if: needs.files-changed.outputs.unit == 'true'
    name: Unit
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4.1.7
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v4.0.3
        with:
          node-version-file: './.tool-versions'
      - name: Install Dependencies & Build Library
        run: |
          npm install
          npm test
        working-directory: ./backend