name: test:unit

on: push

jobs:
  files-changed:
    name: Detect File Changes - unit
    runs-on: ubuntu-latest
    outputs:
      unit: ${{ steps.filter.outputs.unit }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4.1.7
      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: filter
        with:
          filters: |
            unit:
              - '.github/workflows/**/*'
              - 'backend/**/*'

  unit:
    if: needs.files-changed.outputs.unit == 'true'
    name: Unit
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4.1.7
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v4.0.3
        with:
          node-version-file: './.tool-versions'
      - name: Install Dependencies & Build Library
        run: |
          npm install
          npm test
        working-directory: ./backend