name: lint test CI

on: push

jobs:
  build-test:
    name: Lint Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v4.0.3
        with:
          node-version-file: './.tool-versions'

      - name: npm-install
        run: npm install
      
      - name: npm-test
        run: npm test
