name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Node 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: IT4Change/IT4C.dev
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: npm install && npm run build-node16
        BUILD_DIR: docs/.vuepress/dist
        # CNAME: https://www.it4c.dev
